### ISSUE TITLE
Error in _Calculate function

### ISSUE THREAD

**Issue by BL451** [lakshmanmallidi/PyLidar3#4]
_Calculate function returns very noisy values since it's not ignoring zero distance values. This can be resolved by simply checking dist_i once calculated and continuing to next iteration if it's equal to 0. Additionally, there seem to be some small problems with the math in comparison to how it's shown in the YDLidar developer docs (2019 version specifically, was different in 2018 version which looks like the one you were following). 

I made these changes on my fork and the values cleaned up quite nicely, now looks the same as running the Point Cloud Viewer from the manufacturer.

**Comment by hazrulrosdi95** [comment]
Hello sir, could you please show the coding as you mentioned that you have made changes. @BL451

**Comment by hazrulrosdi95** [comment]
> _Calculate function returns very noisy values since it's not ignoring zero distance values. This can be resolved by simply checking dist_i once calculated and continuing to next iteration if it's equal to 0. Additionally, there seem to be some small problems with the math in comparison to how it's shown in the YDLidar developer docs (2019 version specifically, was different in 2018 version which looks like the one you were following).
> 
> I made these changes on my fork and the values cleaned up quite nicely, now looks the same as running the Point Cloud Viewer from the manufacturer.

Hye Benjamin, do you know how to add the angle information for each of the detected point similar to the PointCloudViewer_V6R01 provided by the YDLidar developer?
![PointCloudViewer_V6R01](https://user-images.githubusercontent.com/22463993/87826945-5ee1ae00-c8ac-11ea-954d-68d6cd4b9421.PNG)

**Comment by lakshmanmallidi** [comment]
Thank you, sorry for the delay in merging. I have merged you request.
